import React, { useCallback } from "react";
import { View, Text, Modal, Image, TextInput, TouchableOpacity, ScrollView } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { stylesSetting } from "@/app/css/styles/StylesSetting";
import * as Clipboard from "expo-clipboard";
import showToast from "@/lib/utils/toastService";
import { qrCode2FAStore } from "@/lib/zustand/qrCode2FA";

interface QRCodeModalProps {
  isVisible: boolean;
  onClose: () => void;
  onEnable2FA: () => void;
}

const QRCodeModal: React.FC<QRCodeModalProps> = ({ isVisible, onClose, onEnable2FA }) => {
  const { qrCodeUrl, secret, isLoadingQrCode, errorQrCode } = qrCode2FAStore();

  const copyToClipboard = useCallback(async () => {
    if (secret) {
      await Clipboard.setStringAsync(secret);
      showToast("Secret key copied to clipboard!", "success");
    }
  }, [secret]);

  return (
    <Modal
      animationType="slide"
      transparent={true}
      visible={isVisible}
      onRequestClose={onClose}
    >
      <View style={stylesSetting.modalContainer}>
        <View style={stylesSetting.modalContent}>
          <Text style={stylesSetting.modalTitle}>Setup Two-Factor Authentication</Text>
          {isLoadingQrCode ? (
            <Text style={{ color: "white" }}>Loading QR Code...</Text>
          ) : errorQrCode ? (
            <Text style={{ color: "white" }}>Error loading QR Code: {errorQrCode.message}</Text>
          ) : qrCodeUrl && secret ? (
            <>
              <Image source={{ uri: qrCodeUrl }} style={stylesSetting.qrCodeImage} resizeMode="contain" />
              <View style={stylesSetting.secretContainer}>
                <Text style={stylesSetting.secretLabel}>Secret Key:</Text>
                <TextInput style={stylesSetting.secretText} value={secret} editable={false} />
                <TouchableOpacity onPress={copyToClipboard} style={stylesSetting.copyButton}>
                  <Ionicons name="copy-outline" size={20} color="#FEBF32" />
                </TouchableOpacity>
              </View>
              <Text style={stylesSetting.modalSubtitle}>
                Scan this QR code with your authenticator app (e.g., Google Authenticator, Authy). Enter the code
                generated by the app to enable Two-Factor Authentication.
              </Text>
              <View style={stylesSetting.modalButtonsContainer}>
                <TouchableOpacity
                  style={[stylesSetting.secondaryButton, stylesSetting.modalButton]}
                  onPress={onClose}
                >
                  <Text style={stylesSetting.buttonModal}>Close</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  style={[stylesSetting.primaryButton, stylesSetting.modalButton]}
                  onPress={onEnable2FA}
                >
                  <Text style={stylesSetting.buttonModal}>OK</Text>
                </TouchableOpacity>
              </View>
            </>
          ) : (
            <Text>Something went wrong while fetching QR code and secret.</Text>
          )}
        </View>
      </View>
    </Modal>
  );
};

export default QRCodeModal;