import { StyleSheet } from "react-native";

export const stylesSetting = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    padding: 20,
    gap: 30,
  },
  card: {
    borderRadius: 8,
    borderColor: "#322646",
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  cardTitle: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Lexend",
    fontWeight: "700",
    marginBottom: 12,
    lineHeight: 22,
  },
  settingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  settingText: {
    flex: 1,
    marginRight: 12,
  },
  settingTitle: {
    color: "rgba(255, 255, 255, 1)",
    fontSize: 14,
    fontWeight: "600",
    fontFamily: "Lexend",
    lineHeight: 20,
  },
  settingSubtitle: {
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: 12,
    fontFamily: "Lexend",
    fontWeight: 400,
    lineHeight: 16,
    marginTop: 5,
  },
  outlineButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(58, 58, 83, 1)",
    borderRadius: 20,
    paddingVertical: 10,
    marginTop: 10,
  },
  outlineButtonText: {
    color: "rgba(255, 255, 255, 1)",
    marginLeft: 8,
    fontWeight: 400,
    fontSize: 16,
    fontFamily: "Lexend",
    lineHeight: 22,
  },
  warningText: {
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: 12,
    marginTop: 5,
    marginBottom: 25,
    fontFamily: "Lexend",
    fontWeight: 400,
    lineHeight: 16,
  },
  deleteButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#FF4D4D",
    borderRadius: 20,
    paddingVertical: 10,
  },
  deleteButtonText: {
    color: "#FF4D4D",
    fontWeight: 400,
    marginLeft: 8,
    fontSize: 16,
    fontFamily: "Lexend",
    lineHeight: 22,
  },
  logoutButton: {
    backgroundColor: "#FEBF32",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
    paddingVertical: 12,
    marginTop: 20,
  },
  logoutText: {
    color: "#000",
    fontWeight: "700",
    marginLeft: 6,
    fontSize: 16,
    fontFamily: "Lexend",
    lineHeight: 22,
  },
  versionText: {
    textAlign: "center",
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: 12,
    marginTop: 20,
    fontFamily: "Lexend",
    fontWeight: 500,
    lineHeight: 16,
  },
});
