import { StyleSheet } from "react-native";

export const stylesSetting = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    padding: 20,
    gap: 30,
  },
  card: {
    borderRadius: 8,
    borderColor: "#322646",
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  cardTitle: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Lexend",
    fontWeight: "700",
    marginBottom: 12,
    lineHeight: 22,
  },
  settingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  settingText: {
    flex: 1,
    marginRight: 12,
  },
  settingTitle: {
    color: "rgba(255, 255, 255, 1)",
    fontSize: 14,
    fontWeight: "600",
    fontFamily: "Lexend",
    lineHeight: 20,
  },
  settingSubtitle: {
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: 12,
    fontFamily: "Lexend",
    fontWeight: 400,
    lineHeight: 16,
    marginTop: 5,
  },
  outlineButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(58, 58, 83, 1)",
    borderRadius: 20,
    paddingVertical: 10,
    marginTop: 10,
  },
  outlineButtonText: {
    color: "rgba(255, 255, 255, 1)",
    marginLeft: 8,
    fontWeight: 400,
    fontSize: 16,
    fontFamily: "Lexend",
    lineHeight: 22,
  },
  warningText: {
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: 12,
    marginTop: 5,
    marginBottom: 25,
    fontFamily: "Lexend",
    fontWeight: 400,
    lineHeight: 16,
  },
  deleteButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#FF4D4D",
    borderRadius: 20,
    paddingVertical: 10,
  },
  deleteButtonText: {
    color: "#FF4D4D",
    fontWeight: 400,
    marginLeft: 8,
    fontSize: 16,
    fontFamily: "Lexend",
    lineHeight: 22,
  },
  logoutButton: {
    backgroundColor: "#FEBF32",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
    paddingVertical: 12,
    marginTop: 20,
  },
  logoutText: {
    color: "#000",
    fontWeight: "700",
    marginLeft: 6,
    fontSize: 16,
    fontFamily: "Lexend",
    lineHeight: 22,
  },
  versionText: {
    textAlign: "center",
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: 12,
    marginTop: 20,
    fontFamily: "Lexend",
    fontWeight: 500,
    lineHeight: 16,
  },

  // Modal
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "#222",
    borderRadius: 10,
    padding: 20,
    width: "80%",
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 15,
    fontFamily: "Lexend",
    lineHeight: 24,
    textAlign: "center",
  },
  qrCodeImage: {
    width: 200,
    height: 200,
    marginBottom: 15,
  },
  secretContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginBottom: 15,
    height: 56,
  },
  secretLabel: {
    color: "#fff",
    marginRight: 10,
  },
  secretText: {
    flex: 1,
    backgroundColor: "#333",
    color: "#eee",
    padding: 10,
    borderRadius: 5,
    marginRight: 10,
  },
  copyButton: {
    padding: 10,
    borderRadius: 5,
    backgroundColor: "#333",
  },
  modalSubtitle: {
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: 14,
    fontFamily: "Lexend",
    fontWeight: 400,
    lineHeight: 16,
    marginBottom: 15,
  },
  modalButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    marginTop: 20,
  },
  modalButton: {
    flex: 1,
    marginHorizontal: 5,
  },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(58, 58, 83, 1)",
    borderRadius: 20,
    paddingVertical: 10,
    marginTop: 10,
  },
  secondaryButtonText: {
    color: "#fff",
    marginLeft: 5,
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(58, 58, 83, 1)",
    borderRadius: 20,
    paddingVertical: 10,
    marginTop: 10,
  },
  buttonModal: {
    color: "#fff",
    fontWeight: "bold",
  },

  verificationCodeContainer: {
    flexDirection: "row",
    justifyContent: "center",
    width: "80%",
    marginBottom: 20,
    alignItems: "center",
  },
  verificationCodeInput: {
    width: 40,
    height: 45,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#ccc",
    textAlign: "center",
    marginHorizontal: 2,
    fontFamily: "Lexend",
    fontSize: 16,
    color: "#fff",
    backgroundColor: "#333",
  },
});
